from setuptools import setup

setup(name='cord_19_ems',
      version='1.0',
      author='Molly Moran, Samantha Richards, Emily Fountain',
      packages=['cord_19_ems', 'cord_19_ems.notebooks', 'cord_19_ems.es_module'],
      description='',
      requirements=['certifi==2019.11.28',
                    'chardet==3.0.4',
                    'Click==7.0',
                    'elasticsearch',
                    'elasticsearch-dsl==7.1.0',
                    'Flask==1.1.1',
                    'html2text==2020.1.16',
                    'idna==2.8',
                    'itsdangerous==1.1.0',
                    'Jinja2==2.11.1',
                    'lxml==4.4.2',
                    'MarkupSafe==1.1.1',
                    'mkl-fft==1.0.15',
                    'mkl-random==1.1.0',
                    'mkl-service==2.3.0',
                    'nltk==3.4.5',
                    'numpy==1.18.1',
                    'pycurl==7.43.0.4',
                    'python-dateutil==2.8.1',
                    'requests==2.22.0',
                    'six==1.14.0',
                    'urllib3==1.25.8',
                    'Werkzeug==1.0.0',
                    'Wikipedia-API==0.5.3',
                    'wptools==0.4.17'],
      )